export declare enum FinanceRefundStatusEnum {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    PROCESSING = "PROCESSING",
    COMPLETED = "COMPLETED",
    REJECTED = "REJECTED",
    CANCELLED = "CANCELLED"
}
export declare enum FinanceRefundReasonEnum {
    CUSTOMER_REQUEST = "CUSTOMER_REQUEST",
    DEFECTIVE_PRODUCT = "DEFECTIVE_PRODUCT",
    WRONG_ITEM = "WRONG_ITEM",
    ORDER_CANCELLED = "ORDER_CANCELLED",
    DUPLICATE_CHARGE = "DUPLICATE_CHARGE",
    OTHER = "OTHER"
}
