name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: merkaly-io/actions/setup@master

      - run: pnpm exec tsc --noEmit --pretty false
        shell: bash

      - run: pnpm lint
        shell: bash

      - run: pnpm build
        shell: bash

      - run: npm pack --dry-run
        shell: bash

      - uses: merkaly-io/actions/publish@master

  release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: merkaly-io/actions/release@master
